version: '3.7'

services:
  nginx:
    image: local:self-hosted-prerender
    restart: unless-stopped
    ports:
      - 5080:80
    networks:
      prerender-app:
          aliases:
            - "prerender.lvh.voronenko.net"
      traefik-public:
    environment:
       - PRERENDER_HOST="prerender:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prerender.rule=Host(`prerender.lvh.voronenko.net`)"
      - "traefik.http.routers.prerender.entrypoints=web"

#      - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:PASSWORD"
#      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"

      - "traefik.http.services.prerender-secure.loadbalancer.server.port=80"
      - "traefik.http.routers.prerender-secure.entrypoints=websecure"
      - "traefik.http.routers.prerender-secure.rule=Host(`prerender.lvh.voronenko.net`)"
#      - "traefik.http.routers.joxit-secure.middlewares=traefik-auth"
      - "traefik.http.routers.prerender-secure.tls=true"
  prerender:
      image: voronenko/self-hosted-prerender
#      ports:
#      - 3000:3000
      networks:
        - prerender-app
      environment:
      - MEMORY_CACHE=0
      - CACHE_MAXSIZE=1000
      - CACHE_TTL=6000
      restart: unless-stopped

networks:
  prerender-app:
  traefik-public:
    external: true
